server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

riak:
  address: localhost
  port: 8087
  bucket:
    token: token
    template: template

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: trusted-tokens-manager
  consumer:
    group-id: trusted-tokens-manager-group-1
    max-poll-interval-ms: 60000
    max-session-timeout-ms: 60000
    throttling-timeout-ms: 1000
  topics:
    payment:
      id: payment_event
      consume:
        enabled: false
        max-poll-records: 50
        concurrency: 1
    withdrawal:
      id: withdrawal
      consume:
        enabled: false
        max-poll-records: 50
        concurrency: 1
  ssl:
    enabled: false

retry-policy:
  maxAttempts: 10

trusted.tokens:
  keep-card-tokens-data-years: 3

testcontainers:
  kafka:
    tag: '6.2.0'
