server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

riak:
  address: localhost
  port: 8087
  bucket:
    token: token
    template: template

kafka:
  bootstrap.servers: "localhost:29092"
  client.id: trusted-tokens
  consumer:
    group-id: trusted-tokens-group-1
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 20
  topic:
    payment:
      id: payment_event
      enabled: false
      concurrency: 1
    withdrawal:
      id: withdrawal
      enabled: false
      concurrency: 1
  ssl:
    enabled: false
  acknowledgment:
    nack.sleep: 500
retry-policy:
  maxAttempts: 10
trusted.tokens:
  keep-card-tokens-data-years: 3